/**
 * Shirado & Christakis (2017) — the design, as pure functions.
 *
 *   Shirado, H. & Christakis, N. A. (2017). Locally noisy autonomous agents
 *   improve global human coordination in network experiments. Nature 545,
 *   370-374. https://doi.org/10.1038/nature22332
 *
 * A RECONSTRUCTION of the HUMAN-ONLY arm of that design, from the paper. Not a
 * replication, and not the whole paper: the bots are absent, for a measured
 * platform reason recorded in the README and in `docs/PLATFORM-NOTES.md` §17.
 *
 * Same shape as the Rand 2011 port for the same reason: no imports here, so every
 * rule is unit-testable in milliseconds and the part that gets COPIED is small,
 * pure and checkable by hand (`docs/M5-ADOPTION.md` §2).
 *
 * WHY THIS DESIGN IS THE SHARPEST TEST OF THE WHOLE PACKAGE. In most network
 * experiments a locality leak makes the data wrong. Here it makes the task
 * TRIVIAL: "subjects could see only the colours of neighbours to whom they were
 * directly connected, in addition to their own colour", and someone who can see
 * the whole graph solves it at once. The dependent variable is time to solution,
 * so a leak does not corrupt the measurement — it collapses it toward zero while
 * every screen still looks correct.
 */

/**
 * "each subject was allowed to choose a colour from three choices (green, orange
 * and purple) at any time. The number of colours made available was the minimum
 * necessary to colour the entire network without conflicts, which is known as the
 * chromatic number."
 *
 * Three is not a parameter to tune: it is the chromatic number of the graphs this
 * design uses, and a fourth colour would make the task easy rather than hard.
 */
export const COLORS = ["green", "orange", "purple"];

/**
 * "Subjects were assigned a location in a network of 20 nodes, generated by a
 * preferential attachment model; the network structure was created de novo for
 * each session by attaching new nodes (each with two links) to existing nodes,
 * and subjects were placed into the resulting networks at random."
 *
 * Barabási–Albert with m = 2. `topology.barabasiAlbert(20, 2, { rng })` is exactly
 * that, and the package's seeded generator also permutes who sits where — which is
 * the "placed at random" half.
 */
export const NODES = 20;
export const ATTACHMENT = 2;

/** "they had to complete the task within 5 min". */
export const TIME_LIMIT_SECONDS = 300;

/**
 * Every edge whose two endpoints share a colour, as index pairs.
 *
 * "The collective goal is for every node to have a colour different from all of
 * its neighbour nodes." So the cost function is the number of conflicts, and zero
 * conflicts is the solved state.
 *
 * `colorAt(i)` returns the colour of node `i`, or `undefined` before they choose.
 * An unchosen node is NOT in conflict with anybody: treating it as one would make
 * a session look unsolved because somebody had not loaded yet.
 */
export function conflictEdges(edges, colorAt) {
  return edges.filter(([i, j]) => {
    const a = colorAt(i);
    const b = colorAt(j);
    return a !== undefined && b !== undefined && a === b;
  });
}

/** Total colour conflicts. The paper's cost function. */
export function conflictCount(edges, colorAt) {
  return conflictEdges(edges, colorAt).length;
}

/**
 * Whether the network is properly coloured — the end condition.
 *
 * Requires that EVERY node has chosen. Zero conflicts among a partly-coloured
 * network is not a solution, and accepting it would end sessions early and record
 * a time to solution for a problem nobody solved. That is the silent-success
 * version of this codebase's characteristic failure, so it is a separate clause
 * rather than folded into the conflict count.
 */
export function isSolved(n, edges, colorAt) {
  for (let i = 0; i < n; i++) if (colorAt(i) === undefined) return false;
  return conflictCount(edges, colorAt) === 0;
}

/**
 * A node's own conflicts — what a participant can work out for themselves.
 *
 * Load-bearing for the design rather than a convenience: this is the ONLY view of
 * the cost function a participant is entitled to. The global count is computed
 * server-side and never published, because "although a subject might have solved
 * the problem from his or her own point of view, the game might continue because
 * the network still had conflicts in other regions of the graph" — a participant
 * who could see the global count would know when to keep going, and that is the
 * whole difficulty the paper is measuring.
 */
export function localConflicts(neighbourColors, ownColor) {
  if (ownColor === undefined) return 0;
  return neighbourColors.filter((c) => c === ownColor).length;
}

/**
 * The colours a node could switch to without conflicting with any neighbour.
 *
 * Offered to the CLIENT as a hint about the participant's own neighbourhood only —
 * it is derived entirely from what they can already see, so it reveals nothing.
 * Empty means every colour conflicts, which is the locally-unresolvable state the
 * paper's Fig. 1a marks in dark red and which requires somebody else to move first.
 */
export function conflictFreeColors(neighbourColors) {
  const taken = new Set(neighbourColors.filter((c) => c !== undefined));
  return COLORS.filter((c) => !taken.has(c));
}

/**
 * One row per colour change, for analysis.
 *
 * The dependent variable is time to solution, so the timestamps are the data and
 * `t_ms` is milliseconds since the stage started rather than a wall clock — a
 * duration is what an analyst wants and it does not leak when the session ran.
 *
 * `conflicts_after` is the global count following the change, which participants
 * never saw. Recording it is the point: it is the cost function over time, and it
 * cannot be reconstructed from the colours alone without also knowing the graph at
 * that instant.
 */
export function changeRows(gameID, changes) {
  return changes.map((c) => ({
    game_id: gameID,
    t_ms: c.tMs,
    player_id: c.playerID,
    topology_index: c.topologyIndex,
    degree: c.degree,
    color: c.color,
    conflicts_after: c.conflictsAfter,
  }));
}

/**
 * One row per session.
 *
 * `solved` and `t_solution_ms` are the paper's outcome. `t_solution_ms` is null
 * for an unsolved session rather than 300000: the paper censors at 300 s
 * ("Sessions are censored at 300 s") and writing the limit as though it were an
 * observation is how a censored value silently becomes a measurement.
 */
export function sessionRows(gameID, session) {
  return [
    {
      game_id: gameID,
      n: session.n,
      edges: session.edges,
      solved: session.solved ? 1 : 0,
      t_solution_ms: session.solved ? session.tSolutionMs : "",
      changes: session.changes,
      max_degree: session.maxDegree,
    },
  ];
}

/**
 * Every analysis file for one finished session, as `{ filename: contents }`.
 *
 * Pure, for the reason given in the Rand port's equivalent: the export runs in
 * `onGameEnded`, which only fires when a game ends naturally, so an export
 * written inline in the callback is exercised only by accident. Here the content
 * is asserted by `test/unit/shirado2017.test.ts` and the callback is left with
 * `mkdirSync` and a write loop.
 *
 * `toCSV` is passed in so this file keeps its property of importing nothing.
 */
export function exportFiles(gameID, session, changes, edgeCsv, toCSV) {
  return {
    "session.csv": toCSV(sessionRows(gameID, session)),
    "changes.csv": toCSV(changeRows(gameID, changes)),
    "edges.csv": edgeCsv,
  };
}

/**
 * Rebuild `exportFiles`' arguments from the append-only run log.
 *
 * THE POINT, and it bites harder here than in the Rand port: this experiment's
 * dependent variable IS the change log — when each colour was chosen, and what the
 * global conflict count was afterwards. Held only in process memory until game
 * end, a killed or crashed session lost every bit of it. A session that ran four
 * of its five minutes and then died is exactly the data you would most want.
 *
 * So `callbacks.js` appends one NDJSON record per colour change as it happens, and
 * this turns that log back into what the game-end path passes to `exportFiles`.
 * `test/unit/shirado2017.test.ts` asserts the two paths produce byte-identical
 * CSVs.
 *
 * Note what an unsolved recovery yields: `solved: 0` and an EMPTY
 * `t_solution_ms`, never 300000. A session cut short at four minutes is censored,
 * not a four-minute observation — and it is not even a censored observation at the
 * paper's 300 s, so `t_ms` in `changes.csv` is the only honest statement about how
 * long it ran.
 *
 * Returns `history` as well as the session and its changes: the `graph` record
 * carries the package's own edge events, so `edges.csv` recovers through the
 * package's `edgeRows()` rather than being left empty. A log written before M6
 * Tier 4 has no `events` field and yields `[]` — the old behaviour, for the old
 * data, without a crash.
 *
 * Pure, and tolerant of a truncated final line.
 */
export function fromLog(records) {
  const changes = [];
  let solved = false;
  let tSolutionMs = "";
  let n = 0;
  let edges = 0;
  let maxDegree = 0;
  let history = [];

  for (const r of records) {
    if (r.type === "graph") {
      n = r.n ?? 0;
      edges = r.edges ?? 0;
      maxDegree = r.maxDegree ?? 0;
      // Replaced, not appended: this design logs one `graph` record per session,
      // and a second one could only mean the session restarted — in which case the
      // later graph is the one its changes refer to.
      if (Array.isArray(r.events)) history = r.events;
    } else if (r.type === "change") {
      changes.push(r);
    } else if (r.type === "solved") {
      solved = true;
      tSolutionMs = r.tSolutionMs;
    }
  }

  return {
    changes,
    history,
    session: { n, edges, solved, tSolutionMs, changes: changes.length, maxDegree },
  };
}
