/**
 * Shirado & Christakis (2017) — the design, as pure functions.
 *
 *   Shirado, H. & Christakis, N. A. (2017). Locally noisy autonomous agents
 *   improve global human coordination in network experiments. Nature 545,
 *   370-374. https://doi.org/10.1038/nature22332
 *
 * A RECONSTRUCTION of the HUMAN-ONLY arm of that design, from the paper. Not a
 * replication, and not the whole paper: the bots are absent, for a measured
 * platform reason recorded in the README and in `docs/PLATFORM-NOTES.md` §17.
 *
 * Same shape as the Rand 2011 port for the same reason: no imports here, so every
 * rule is unit-testable in milliseconds and the part that gets COPIED is small,
 * pure and checkable by hand.
 *
 * WHY THIS DESIGN IS THE SHARPEST TEST OF THE WHOLE PACKAGE. In most network
 * experiments a locality leak makes the data wrong. Here it makes the task
 * TRIVIAL: "subjects could see only the colors of neighbors to whom they were
 * directly connected, in addition to their own color", and someone who can see
 * the whole graph solves it at once. The dependent variable is time to solution,
 * so a leak does not corrupt the measurement — it collapses it toward zero while
 * every screen still looks correct.
 */

/**
 * "each subject was allowed to choose a color from three choices (green, orange
 * and purple) at any time. The number of colors made available was the minimum
 * necessary to color the entire network without conflicts, which is known as the
 * chromatic number."
 *
 * Three is not a parameter to tune: it is the chromatic number of the graphs this
 * design uses, and a fourth color would make the task easy rather than hard.
 */
export const COLORS = ["green", "orange", "purple"];

/**
 * "Subjects were assigned a location in a network of 20 nodes, generated by a
 * preferential attachment model; the network structure was created de novo for
 * each session by attaching new nodes (each with two links) to existing nodes,
 * and subjects were placed into the resulting networks at random."
 *
 * Barabási–Albert with m = 2. `topology.barabasiAlbert(20, 2, { rng })` is exactly
 * that, and the package's seeded generator also permutes who sits where — which is
 * the "placed at random" half.
 */
export const NODES = 20;
export const ATTACHMENT = 2;

/** "they had to complete the task within 5 min". */
export const TIME_LIMIT_SECONDS = 300;

/**
 * Every edge whose two endpoints share a color, as index pairs.
 *
 * "The collective goal is for every node to have a color different from all of
 * its neighbor nodes." So the cost function is the number of conflicts, and zero
 * conflicts is the solved state.
 *
 * `colorAt(i)` returns the color of node `i`, or `undefined` before they choose.
 * An unchosen node is NOT in conflict with anybody: treating it as one would make
 * a session look unsolved because somebody had not loaded yet.
 */
export function conflictEdges(edges, colorAt) {
  return edges.filter(([i, j]) => {
    const a = colorAt(i);
    const b = colorAt(j);
    return a !== undefined && b !== undefined && a === b;
  });
}

/** Total color conflicts. The paper's cost function. */
export function conflictCount(edges, colorAt) {
  return conflictEdges(edges, colorAt).length;
}

/**
 * Whether the network is properly colored — the end condition.
 *
 * Requires that EVERY node has chosen. Zero conflicts among a partly-colored
 * network is not a solution, and accepting it would end sessions early and record
 * a time to solution for a problem nobody solved. That is the silent-success
 * version of this codebase's characteristic failure, so it is a separate clause
 * rather than folded into the conflict count.
 */
export function isSolved(n, edges, colorAt) {
  for (let i = 0; i < n; i++) if (colorAt(i) === undefined) return false;
  return conflictCount(edges, colorAt) === 0;
}

/**
 * A node's own conflicts — what a participant can work out for themselves.
 *
 * Load-bearing for the design rather than a convenience: this is the ONLY view of
 * the cost function a participant is entitled to. The global count is computed
 * server-side and never published, because "although a subject might have solved
 * the problem from his or her own point of view, the game might continue because
 * the network still had conflicts in other regions of the graph" — a participant
 * who could see the global count would know when to keep going, and that is the
 * whole difficulty the paper is measuring.
 */
export function localConflicts(neighborColors, ownColor) {
  if (ownColor === undefined) return 0;
  return neighborColors.filter((c) => c === ownColor).length;
}

/**
 * The colors a node could switch to without conflicting with any neighbor.
 *
 * Offered to the CLIENT as a hint about the participant's own neighborhood only —
 * it is derived entirely from what they can already see, so it reveals nothing.
 * Empty means every color conflicts, which is the locally-unresolvable state the
 * paper's Fig. 1a marks in dark red and which requires somebody else to move first.
 */
export function conflictFreeColors(neighborColors) {
  const taken = new Set(neighborColors.filter((c) => c !== undefined));
  return COLORS.filter((c) => !taken.has(c));
}

// ---------------------------------------------------------------- the agents
//
// "Locally noisy autonomous agents" — the paper's title, and its contribution.
// Everything below is what `docs/PLATFORM-NOTES.md` §17 said was missing and what
// `ISSUES.md` O10 asked for. It runs in a SEPARATE PROCESS as a headless
// participant (`server/bots.mjs`, on `empirica-networks/bots`), because that is
// the only kind of thing Empirica can seat at a node: a bot with no participant
// behind it has no player scope, no seat and no private channel.
//
// Read the reconstruction notes on each constant. Three of the numbers here are
// the paper's and one is not, and the difference is not something to leave to
// whoever reads the code next.

/** Three agents per 20-node session. The paper's design. */
export const BOT_COUNT = 3;

/**
 * "we manipulated the level of behavioral randomness of the bots (0%, 10%, 30%)".
 *
 * The middle level is the paper's finding: 10% noise in central positions improved
 * global coordination, while 30% made it worse. 0% is the deterministic-agent
 * control, which is NOT the same thing as the human-only arm — an agent that never
 * errs is still an agent.
 */
export const NOISE_LEVELS = [0, 0.1, 0.3];

/**
 * "central, random, peripheral" — where the three agents sit.
 *
 * Placement is over DEGREE, which is why the graph has to be generated before the
 * seats are assigned and then relabelled onto them (`placeBots` below). Barabási–
 * Albert produces hubs, so the three highest-degree nodes and the three
 * lowest-degree ones are genuinely different positions.
 */
export const PLACEMENTS = ["central", "peripheral", "random"];

/**
 * How often an agent reconsiders its color, in milliseconds.
 *
 * **NOT the paper's number.** The paper describes agents that act with human-like
 * latency; the exact distribution is not reconstructed here, and an agent's speed
 * is obviously not neutral — one that moved every 50 ms would dominate the session
 * regardless of its noise level. So this is a stated choice, not a measurement,
 * and it is a constant rather than a magic number so that a study which cares can
 * change it in one place and say what it used.
 *
 * 1500 ms is roughly the pace of a person who is paying attention, and it is slow
 * enough that three agents do not out-move seventeen humans.
 */
export const BOT_INTERVAL_MS = 1500;

/**
 * Uniform choice from a list, using a supplied rng. Local so this file keeps its
 * property of importing nothing.
 */
function pick(items, rng) {
  return items[Math.floor(rng() * items.length)];
}

/**
 * What an agent does next, given only what it can see.
 *
 * ONLY what it can see: its own color and its neighbors'. There is no version of
 * this function that takes the graph or the global conflict count, and that is a
 * design constraint rather than an omission — an agent with more information than
 * a participant would make the bot conditions a comparison between two different
 * games.
 *
 * The rule, in the paper's terms: agents "behaved in the same way as humans" —
 * switch away from a conflict — with a probability `noise` of acting at random
 * instead. So:
 *
 *   - with probability `noise`, choose uniformly from all three colors;
 *   - otherwise, if the current color conflicts with a neighbor, move to a
 *     conflict-free color if one exists, and to a random other color if none
 *     does (the locally-unresolvable state — standing still there is what a
 *     deadlock is made of);
 *   - otherwise, stay.
 *
 * **One ambiguity, resolved explicitly.** Whether the noisy draw includes the
 * color the agent already has is not something the reconstruction settles. It is
 * uniform over all three here, so an ε of 0.3 produces an observable change about
 * 0.2 of the time. Excluding the current color would make ε the rate of visible
 * change instead. The choice matters for any comparison with the paper's numbers,
 * so it is stated rather than buried.
 *
 * Returns a color, which may be the one it already has — meaning "no move".
 * `bots.mjs` writes only on a change, so a no-move produces no record and no
 * traffic.
 */
export function botChoice({ ownColor, neighborColors, noise, rng }) {
  if (rng() < noise) return pick(COLORS, rng);
  if (ownColor === undefined) return pick(COLORS, rng);
  if (localConflicts(neighborColors, ownColor) === 0) return ownColor;
  const free = conflictFreeColors(neighborColors);
  if (free.length > 0) return pick(free, rng);
  // Every color conflicts. Moving anyway is the point: this is the state the
  // paper's Fig. 1a marks in dark red, and it resolves only when somebody moves
  // without local improvement.
  return pick(
    COLORS.filter((c) => c !== ownColor),
    rng
  );
}

/**
 * Relabel a generated graph so the agents land on the seats the condition asks for.
 *
 * Seats are fixed before the topology function is called — `players[i]` is
 * whoever will occupy index `i` — so placement cannot be done by reordering
 * participants. It is done the other way round: generate the graph, decide which
 * of ITS vertices the agents should have, and permute the labels so those
 * vertices become the agents' seats.
 *
 *   `edges`      the generated graph, over vertices 0..n-1
 *   `botSeats`   the seat indices the agents occupy (from `players`)
 *   `placement`  "central" | "peripheral" | "random"
 *
 * Returns an edge list over SEATS. Same graph, up to isomorphism — the structure
 * is untouched, only who sits where — which is what makes placement a manipulation
 * of position rather than of network structure. A study whose "central" condition
 * also changed the degree distribution would be confounded at the root.
 *
 * Humans are shuffled into the remaining seats, which is the paper's "subjects
 * were placed into the resulting networks at random".
 */
export function placeBots(edges, n, botSeats, placement, rng) {
  if (!PLACEMENTS.includes(placement)) {
    throw new Error(
      `shirado2017: unknown bot placement "${placement}". Expected one of ${PLACEMENTS.join(", ")}.`
    );
  }
  const deg = new Array(n).fill(0);
  for (const [i, j] of edges) {
    deg[i]++;
    deg[j]++;
  }

  // Vertices ordered by how much of a hub they are. Ties broken by the rng rather
  // than by index, or "central" would systematically prefer low-numbered vertices
  // — which in a preferential-attachment graph are the early, high-degree ones,
  // so the tie-break would silently reinforce the very thing being manipulated.
  const jitter = Array.from({ length: n }, () => rng());
  const byDegree = [...Array(n).keys()].sort(
    (a, b) => deg[b] - deg[a] || jitter[a] - jitter[b]
  );

  let targets;
  if (placement === "central") targets = byDegree.slice(0, botSeats.length);
  else if (placement === "peripheral") targets = byDegree.slice(-botSeats.length);
  else targets = shuffleLocal([...Array(n).keys()], rng).slice(0, botSeats.length);

  // vertex -> seat
  const seatOf = new Array(n).fill(-1);
  for (const [t, vertex] of targets.entries()) seatOf[vertex] = botSeats[t];

  const freeSeats = shuffleLocal(
    [...Array(n).keys()].filter((s) => !botSeats.includes(s)),
    rng
  );
  let next = 0;
  for (let v = 0; v < n; v++) if (seatOf[v] === -1) seatOf[v] = freeSeats[next++];

  return edges.map(([i, j]) => [seatOf[i], seatOf[j]]);
}

/** Fisher–Yates with a supplied rng. Local, so this file still imports nothing. */
function shuffleLocal(items, rng) {
  for (let i = items.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    const a = items[i];
    items[i] = items[j];
    items[j] = a;
  }
  return items;
}

/**
 * One row per color change, for analysis.
 *
 * The dependent variable is time to solution, so the timestamps are the data and
 * `t_ms` is milliseconds since the stage started rather than a wall clock — a
 * duration is what an analyst wants and it does not leak when the session ran.
 *
 * `conflicts_after` is the global count following the change, which participants
 * never saw. Recording it is the point: it is the cost function over time, and it
 * cannot be reconstructed from the colors alone without also knowing the graph at
 * that instant.
 *
 * `is_bot` marks the agents' moves. Not derivable afterwards: an agent and a human
 * write the same key on the same kind of channel through the same code path, which
 * is exactly the property the bots were built to have, so nothing in the data says
 * which is which unless it is recorded here. An analysis of human behavior that
 * forgot to exclude them would be averaging over a population it chose.
 */
export function changeRows(gameID, changes) {
  return changes.map((c) => ({
    game_id: gameID,
    t_ms: c.tMs,
    player_id: c.playerID,
    topology_index: c.topologyIndex,
    degree: c.degree,
    color: c.color,
    is_bot: c.isBot ? 1 : 0,
    conflicts_after: c.conflictsAfter,
  }));
}

/**
 * One row per session.
 *
 * `solved` and `t_solution_ms` are the paper's outcome. `t_solution_ms` is null
 * for an unsolved session rather than 300000: the paper censors at 300 s
 * ("Sessions are censored at 300 s") and writing the limit as though it were an
 * observation is how a censored value silently becomes a measurement.
 *
 * The four `bot_*` columns are the condition. `bot_indices` is the seating, so an
 * analysis can recover which nodes were agents and check the placement actually
 * happened rather than trusting the label — the paper's central and peripheral
 * conditions differ only in degree, and a placement bug would produce a perfectly
 * plausible table with the manipulation silently absent. `bots=0` is the human-only
 * arm, where the other three are empty rather than 0: an empty cell is "no agents
 * in this session", and a 0 there would read as "agents with zero noise", which is
 * a different condition the paper also ran.
 */
export function sessionRows(gameID, session) {
  const hasBots = (session.bots ?? 0) > 0;
  return [
    {
      game_id: gameID,
      n: session.n,
      edges: session.edges,
      solved: session.solved ? 1 : 0,
      t_solution_ms: session.solved ? session.tSolutionMs : "",
      changes: session.changes,
      max_degree: session.maxDegree,
      bots: session.bots ?? 0,
      bot_placement: hasBots ? (session.botPlacement ?? "") : "",
      bot_noise: hasBots ? (session.botNoise ?? "") : "",
      bot_indices: hasBots ? (session.botIndices ?? []).join(" ") : "",
    },
  ];
}

/**
 * Every analysis file for one finished session, as `{ filename: contents }`.
 *
 * Pure, for the reason given in the Rand port's equivalent: the export runs in
 * `onGameEnded`, which only fires when a game ends naturally, so an export
 * written inline in the callback is exercised only by accident. Here the content
 * is asserted by `test/unit/shirado2017.test.ts` and the callback is left with
 * `mkdirSync` and a write loop.
 *
 * `toCSV` is passed in so this file keeps its property of importing nothing.
 */
export function exportFiles(gameID, session, changes, edgeCsv, toCSV) {
  return {
    "session.csv": toCSV(sessionRows(gameID, session)),
    "changes.csv": toCSV(changeRows(gameID, changes)),
    "edges.csv": edgeCsv,
  };
}

/**
 * Rebuild `exportFiles`' arguments from the append-only run log.
 *
 * THE POINT, and it bites harder here than in the Rand port: this experiment's
 * dependent variable IS the change log — when each color was chosen, and what the
 * global conflict count was afterwards. Held only in process memory until game
 * end, a killed or crashed session lost every bit of it. A session that ran four
 * of its five minutes and then died is exactly the data you would most want.
 *
 * So `callbacks.js` appends one NDJSON record per color change as it happens, and
 * this turns that log back into what the game-end path passes to `exportFiles`.
 * `test/unit/shirado2017.test.ts` asserts the two paths produce byte-identical
 * CSVs.
 *
 * Note what an unsolved recovery yields: `solved: 0` and an EMPTY
 * `t_solution_ms`, never 300000. A session cut short at four minutes is censored,
 * not a four-minute observation — and it is not even a censored observation at the
 * paper's 300 s, so `t_ms` in `changes.csv` is the only honest statement about how
 * long it ran.
 *
 * Returns `history` as well as the session and its changes: the `graph` record
 * carries the package's own edge events, so `edges.csv` recovers through the
 * package's `edgeRows()` rather than being left empty. A log written before M6
 * Tier 4 has no `events` field and yields `[]` — the old behavior, for the old
 * data, without a crash.
 *
 * The `graph` record also carries the CONDITION — how many agents, where, and how
 * noisy — because a recovered session that could not say which arm it belonged to
 * would be a lost observation rather than a rescued one. A log written before the
 * bots existed has none of those fields and recovers as the human-only arm, which
 * is what it was.
 *
 * Pure, and tolerant of a truncated final line.
 */
export function fromLog(records) {
  const changes = [];
  let solved = false;
  let tSolutionMs = "";
  let n = 0;
  let edges = 0;
  let maxDegree = 0;
  let history = [];
  let bots = 0;
  let botPlacement = "";
  let botNoise = "";
  let botIndices = [];

  for (const r of records) {
    if (r.type === "graph") {
      n = r.n ?? 0;
      edges = r.edges ?? 0;
      maxDegree = r.maxDegree ?? 0;
      bots = r.bots ?? 0;
      botPlacement = r.botPlacement ?? "";
      botNoise = r.botNoise ?? "";
      botIndices = Array.isArray(r.botIndices) ? r.botIndices : [];
      // Replaced, not appended: this design logs one `graph` record per session,
      // and a second one could only mean the session restarted — in which case the
      // later graph is the one its changes refer to.
      if (Array.isArray(r.events)) history = r.events;
    } else if (r.type === "change") {
      changes.push(r);
    } else if (r.type === "solved") {
      solved = true;
      tSolutionMs = r.tSolutionMs;
    }
  }

  return {
    changes,
    history,
    session: {
      n,
      edges,
      solved,
      tSolutionMs,
      changes: changes.length,
      maxDegree,
      bots,
      botPlacement,
      botNoise,
      botIndices,
    },
  };
}
